apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
    - name: test-container
      image: maho/my-ubuntu:0.1
      command: ["tail",  "-f", "/dev/null"]
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: example-secret-1
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: example-secret-1
              key: password
